### ISSUE TITLE
need to your help!

### ISSUE THREAD

**Issue by fatememir** [zhushenwudi/bustag#1]
hi zhushenwudi . i saw your issue in just_audio flutter and it is closed . i have a problem as you are . can you help me to solve it?
i searched a lot but cant find the solution . please help me . thank you 

your issue: https://github.com/ryanheise/just_audio/issues/719
if you intrested in helping me , let me tell you more .
my repository : https://github.com/fatememir/just_audio_test

the problem: I read a m3u8 file from url and when i drag the music backwards or forwards , sound plays well but the state stucks in loading state . also buffering and position get wrong (position stuck ).
I tried with a url that return a mp3 file but the result was same .

**Comment by zhushenwudi** [comment]
Please reply to me in that close's issue, and please tell me what device and system or other details

**Comment by fatememir** [comment]
I cant mention you because your issue is locked. can i mention you in my issue? thanks

**Comment by zhushenwudi** [comment]
I was busy before November. I'll take a moment to look at it later. You'd better contact the library author to see if he has any ideas

**Comment by fatememir** [comment]
> I was busy before November. I'll take a moment to look at it later. You'd better contact the library author to see if he has any ideas

thank you for your answer. can I have your email to send you more detail about my problem?
I asked from library author but he didnt answer and I should solve my problem

**Comment by zhushenwudi** [comment]
of course, 55681140@163.com

**Comment by zhushenwudi** [comment]
i upgrade to just_audio 0.9.30, and didn't find the problem you said
